keys:
  - &bugatti_nix age1q3575mlegx4mzxtmzey5rzg9nwrnwlc9mlr5jeqcfltnzt6gwcqq6jdrka
  - &oci_headscale age1qwuz9ud98q82xpresskwkgd20r35u0valpddq973h2a9dad6cyjqxqmzt2
  - &oci_authentik age1hj5dyl0wzlq92ms2hrut6he05dqv0pknlv7wpyv2jywhz2hqwe9qgpt5dl
  - &erik_mbp age17fq29yexw9rf30je5xp86hdda6tgug52sax7vy0af2sngempqv0qwhe4vr
  - &gha_ci age1tpupgevxd2d50zv95c098c3xkfqed4zk46h8fag9stadj75dvu0q3wx0mk
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *oci_headscale
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
  - path_regex: secrets/hosts/gibraltar/bugatti-nix-secrets\.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *erik_mbp
      - *gha_ci
  - path_regex: secrets/hosts/oracle-cloud/free-x86.yaml$
    key_groups:
    - age:
      - *oci_headscale
      - *erik_mbp
      - *gha_ci

  - path_regex: secrets/hosts/oracle-cloud/free-aarch64.yaml$
    key_groups:
    - age:
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
