keys:
  - &bugatti_nix age1q3575mlegx4mzxtmzey5rzg9nwrnwlc9mlr5jeqcfltnzt6gwcqq6jdrka
  - &oci_headscale age1qwuz9ud98q82xpresskwkgd20r35u0valpddq973h2a9dad6cyjqxqmzt2
  - &oci_authentik age1hj5dyl0wzlq92ms2hrut6he05dqv0pknlv7wpyv2jywhz2hqwe9qgpt5dl
  - &pc_24 age1y2g734aqge4lsvmf8dw6s5rc8rkd0scmfwvxm3nlat6tu7y60a2s94yn0l
  - &erik_mbp age17fq29yexw9rf30je5xp86hdda6tgug52sax7vy0af2sngempqv0qwhe4vr
  - &gha_ci age1tpupgevxd2d50zv95c098c3xkfqed4zk46h8fag9stadj75dvu0q3wx0mk
  - &zagato_master_1 age1fl54gf3ry53npnhv3gxndqf8hxxuzknu0yzseszqsx0xu9ksj9hq4h2utn
  - &zagato_master_2 age1m0p20tpl4exwypvgqzhcmm7cw78rcm6gfm3kt0s2cm86rs80g59s88rfaf
  - &zagato_master_3 age169gfm0xz40e3egauc3ddux50vdqlnmeth5qqv9ut94wt0hpuz5es4var5k
  - &erikp_home_desktop age1wj8d6dpv8xt5m2kpusxzfkfuedp5j4qjszrtg0tnzevgkd3sla8q0wms67
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *oci_headscale
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
      - *pc_24
      - *erikp_home_desktop
  - path_regex: secrets/hosts/pilatus/pc24\.yaml$
    key_groups:
    - age:
      - *erik_mbp
      - *gha_ci
      - *pc_24
      - *erikp_home_desktop
  - path_regex: secrets/hosts/gibraltar/bugatti-nix-secrets\.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop
  - path_regex: secrets/hosts/oracle-cloud/free-x86.yaml$
    key_groups:
    - age:
      - *oci_headscale
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop

  - path_regex: secrets/hosts/oracle-cloud/free-aarch64.yaml$
    key_groups:
    - age:
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop

  - path_regex: secrets/hosts/ucaia/zagato/k3s-secrets\.yaml$
    key_groups:
    - age:
      - *zagato_master_1
      - *zagato_master_2
      - *zagato_master_3
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop
