keys:
  - &bugatti_nix age1q3575mlegx4mzxtmzey5rzg9nwrnwlc9mlr5jeqcfltnzt6gwcqq6jdrka
  - &oci_headscale age1qwuz9ud98q82xpresskwkgd20r35u0valpddq973h2a9dad6cyjqxqmzt2
  - &oci_authentik age1hj5dyl0wzlq92ms2hrut6he05dqv0pknlv7wpyv2jywhz2hqwe9qgpt5dl
  - &pc_24 age1y2g734aqge4lsvmf8dw6s5rc8rkd0scmfwvxm3nlat6tu7y60a2s94yn0l
  - &erik_mbp age17fq29yexw9rf30je5xp86hdda6tgug52sax7vy0af2sngempqv0qwhe4vr
  - &gha_ci age1wcuzeqxgdmv6ev0ufawnu699pyxrqq565tae79sa2jfgnffvlvmq5xd03h
  - &zagato_master_1 age1w8kqhxusrglw4697ku3r0v6r0x42am4d6l8k6en96uvf7dxyrqeqwf3nsy
  - &zagato_master_2 age1uev6mgsfdkakk2kps2f6d05t9wckh5ex0dfxfwnfgyt20kyaxp6q0xzkd8
  - &zagato_master_3 age1ddlymgwgj5p7438pltp6rfdpdwul54gsp0ue8az4jg22x82m7v9qgfev9n
  - &zagato_worker_1 age1htmygjfah9sxpnkky6nrcn3p5wj2d3ml5d06nux6djefcd2p854qtt8ta3
  - &zagato_worker_2 age1s6af7sfp4elds8507wjtluuavju82kreqsjx9k8z6e84nwngtglqfracwg
  - &zagato_shared_cloudinit age1jha9zrxs682wl53767u5gzm26terltfs2lcmd4djyj8t69t4se9qqrq83s
  - &erikp_home_desktop age1wj8d6dpv8xt5m2kpusxzfkfuedp5j4qjszrtg0tnzevgkd3sla8q0wms67
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *oci_headscale
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
      - *pc_24
      - *erikp_home_desktop
  - path_regex: secrets/hosts/pilatus/pc24\.yaml$
    key_groups:
    - age:
      - *erik_mbp
      - *gha_ci
      - *pc_24
      - *erikp_home_desktop
  - path_regex: secrets/hosts/gibraltar/bugatti-nix-secrets\.yaml$
    key_groups:
    - age:
      - *bugatti_nix
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop
  - path_regex: secrets/hosts/oracle-cloud/free-x86.yaml$
    key_groups:
    - age:
      - *oci_headscale
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop

  - path_regex: secrets/hosts/oracle-cloud/free-aarch64.yaml$
    key_groups:
    - age:
      - *oci_authentik
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop

  - path_regex: secrets/hosts/ucaia/zagato/k3s-secrets\.yaml$
    key_groups:
    - age:
      - *zagato_master_1
      - *zagato_master_2
      - *zagato_master_3
      - *zagato_worker_1
      - *zagato_worker_2
      - *zagato_shared_cloudinit
      - *erik_mbp
      - *gha_ci
      - *erikp_home_desktop
