name: Build

on:
  pull_request:
  push:
    branches: []

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:gha
          args: --login-server=https://headscale.parawell.cloud
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      
      - name: Setup Flakehub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Configure SSH
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DEPLOY_SSH_KEY: "op://Github_Actions/ssh_key/private key"
          SOPS_AGE_KEY: "op://Github_Actions/nix_age_secret/private_key"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat << 'EOF' >> ~/.ssh/known_hosts
          150.136.213.118 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPR9yQC1u8J1GIo8SToHGgDAkgnxhTYXoX6LOnqYUdfM
          100.64.0.28 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPDm5ArgQ8Ehj/PibOa1G9NlA3Wp87fXM8oOvLxwVUHu
          129.153.154.190 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKaH2Sp/sVQ9bhwLiaWg9P93grswjsfcNZfujwfQ/iri
          EOF
          chmod 644 ~/.ssh/known_hosts
          
          # Test connection to the builder
          ssh erikp@100.64.0.28 echo "SSH connection successful"

      - name: Deploy using remote builder
        env:
          SOPS_AGE_KEY: ${{ env.SOPS_AGE_KEY }}
        run: |
          # Build using deploy-rs with the remote store approach
          nix develop --accept-flake-config --command deploy ".#oci-headscale" \
            --eval-store auto \
            --store ssh-ng://erikp@100.64.0.28 \
            --builders "" \
            --print-build-logs
